#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo
    echo "Please provide exactly one test file!"
    echo
    exit 1
fi
if [ ! -f "$1" ]; then
    echo
    echo "The test file does not exist";
    echo
    exit 1
fi
cp "$1" test.txt 2>/dev/null
./FG
if [ ! -f "TestExecutionEngine.cs" ] || [ ! -f "TestQSharpOperation.qs" ]; then
    exit 1
fi
dotnet clean
dotnet run